### ISSUE TITLE
jdk1.7 crash with spring-data-mongo

### ISSUE THREAD

**Issue by clevertension** [wu-sheng/sky-walking#459] opened 2017-09-25 08:28 UTC
Please answer these questions before submitting your issue.

### What version of sky-walking are you using?
3.2

### What version of your OS?
CentOS release 6.9 (Final)

### What version of your JRE?
1.7.0_80

### What did you do?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

it is a jdk bug
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8041920

1. use skywalking-agent.jar in your application "-javaagent:/xxx/skywalking-agent.jar
2. retrieve huge data use "mongoTemplate" with spring-data-mongo, for example: 10000 row, it will not cause OOM
3. then, you can see the jvm is crash

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000000000003, pid=20686, tid=139760528467712
#
# JRE version: Java(TM) SE Runtime Environment (7.0_79-b15) (build 1.7.0_79-b15)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (24.79-b02 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  0x0000000000000003
#
# Core dump written. Default location: /home/bp/apache-tomcat-7.0.52/core or core.20686
#
# An error report file with more information is saved as:
# /home/bp/apache-tomcat-7.0.52/hs_err_pid20686.log
Compiled method (c2)  275801 2139             java.lang.invoke.LambdaForm$NamedFunction::invoke_L_L (28 bytes)
 total in heap  [0x00007f1c9166d610,0x00007f1c9166d8f8] = 744
 relocation     [0x00007f1c9166d730,0x00007f1c9166d758] = 40
 main code      [0x00007f1c9166d760,0x00007f1c9166d7e0] = 128
 stub code      [0x00007f1c9166d7e0,0x00007f1c9166d818] = 56
 oops           [0x00007f1c9166d818,0x00007f1c9166d820] = 8
 scopes data    [0x00007f1c9166d820,0x00007f1c9166d868] = 72
 scopes pcs     [0x00007f1c9166d868,0x00007f1c9166d8c8] = 96
 dependencies   [0x00007f1c9166d8c8,0x00007f1c9166d8d0] = 8
 handler table  [0x00007f1c9166d8d0,0x00007f1c9166d8e8] = 24
 nul chk table  [0x00007f1c9166d8e8,0x00007f1c9166d8f8] = 16
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
```

so i think this bug will be related with all spring data projects such as spring-data-redis

### workaround
-XX:CompileCommand=exclude,java/lang/invoke/LambdaForm$*.invoke*

**Comment by wu-sheng** [comment] 2017-09-25 08:36
Thanks for @clevertension hard work. This is a very tricky bug, caused by JRE. 

Document this for other users.

**Comment by wu-sheng** [comment] 2017-09-25 08:36
Closing this.

**Closed by wu-sheng** 2017-09-25 08:36 UTC
Labels: question

**Comment by wujun8** [comment] 2019-09-05 03:28
I'm confused about the bug is addressed as
> Affected Version: 8

[here](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8041920) while you're talking about `1.7.0_80 `.
I didn't reproduce the error in `1.7.0_80 `, and neither in later versions(8u212).

Did Anyone have deadlock problem because of mongo agent?
